version: "3"

services:
  mariadb:
    # see https://hub.docker.com/_/mysql/
    #
    image: lut/saas-mariadb 
    build:
      context: .
      dockerfile: docker/Dockerfile.mariadb
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=s22s
      - MYSQL_DATABASE=saas

  web:
    # see https://hub.docker.com/_/php/
    #
    image: lut/saas-web
    build:
      context: .
      dockerfile: docker/Dockerfile.php
    volumes:
      - .:/var/www/html
    links:
      - mariadb  

volumes:
  mysqldata:

